version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          #JAVA_OPTS: -XX:+UseG1GC -Xmx1536m -Xms512m
          JAVA_OPTS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=4 -XshowSettings:vm

    working_directory: ~/jenkins-pipeline-shared-libraries-gradle-plugin
    steps:
      - checkout

      - restore_cache:
          keys:
          - home-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/junit5.gradle.kts" }}
          - build-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/junit5.gradle.kts" }}

      - run:
          command: |
            java -XshowSettings:vm -XX:+PrintCommandLineFlags -version
            java -XshowSettings:vm -XX:+PrintCommandLineFlags -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -version
            javac -version
          name: Show Java Version

      - run:
          command: ./gradlew downloadDependencies --max-workers 2 --info --stacktrace
          name: Download Dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: home-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/junit5.gradle.kts" }}

      - run:
          command: ./gradlew build --max-workers 2 --info --stacktrace --scan
          name: Gradle Build

      - store_test_results:
          path: ~/jenkins-pipeline-shared-libraries-gradle-plugin/build/test-results/

      - save_cache:
          paths:
            - ~/jenkins-pipeline-shared-libraries-gradle-plugin/.gradle
          key: build-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/junit5.gradle.kts" }}


