version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
          JAVA_OPTS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap

    working_directory: ~/jenkins-pipeline-shared-libraries-gradle-plugin
    steps:
      - checkout

      - restore_cache:
          keys:
          - home-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/junit5.gradle.kts" }}
          - build-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/junit5.gradle.kts" }}

      - run:
          command: |
            java -version
            javac -version
          name: Show Java Version

      - run:
          command: ./gradlew build --info
          name: Gradle Build

      - store_test_results:
          path: ~/jenkins-pipeline-shared-libraries-gradle-plugin/build/test-results/

      - save_cache:
          paths:
            - ~/.gradle
          key: home-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/junit5.gradle.kts" }}

      - save_cache:
          paths:
            - ~/jenkins-pipeline-shared-libraries-gradle-plugin/.gradle
          key: build-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/junit5.gradle.kts" }}


