version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/jenkins-pipeline-shared-libraries-gradle-plugin
    steps:
      - checkout

      - restore_cache:
          keys:
          - home-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/junit5.gradle.kts" }}
          - build-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/junit5.gradle.kts" }}

      - run: ./gradlew build --no-daemon

      - store_test_results:
          path: ~/jenkins-pipeline-shared-libraries-gradle-plugin/build/test-results/

      - save_cache:
          paths:
            - ~/jenkins-pipeline-shared-libraries-gradle-plugin/.gradle
          key: build-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/junit5.gradle.kts" }}


